(* Do not modify this file by hand. It is automatically generated by
   util/generateOCamlAPIWrappers_ml.py. *)

let app_add_categories ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "addCategories"]
    | None -> [app_name_or_id; "addCategories"]
  DX.api_call ~always_retry fully_qualified_route input


let app_add_developers ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "addDevelopers"]
    | None -> [app_name_or_id; "addDevelopers"]
  DX.api_call ~always_retry fully_qualified_route input


let app_add_tags ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "addTags"]
    | None -> [app_name_or_id; "addTags"]
  DX.api_call ~always_retry fully_qualified_route input


let app_delete ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "delete"]
    | None -> [app_name_or_id; "delete"]
  DX.api_call ~always_retry fully_qualified_route input


let app_describe ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "describe"]
    | None -> [app_name_or_id; "describe"]
  DX.api_call ~always_retry fully_qualified_route input


let app_get ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "get"]
    | None -> [app_name_or_id; "get"]
  DX.api_call ~always_retry fully_qualified_route input


let app_install ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "install"]
    | None -> [app_name_or_id; "install"]
  DX.api_call ~always_retry fully_qualified_route input


let app_list_categories ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "listCategories"]
    | None -> [app_name_or_id; "listCategories"]
  DX.api_call ~always_retry fully_qualified_route input


let app_list_developers ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "listDevelopers"]
    | None -> [app_name_or_id; "listDevelopers"]
  DX.api_call ~always_retry fully_qualified_route input


let app_publish ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "publish"]
    | None -> [app_name_or_id; "publish"]
  DX.api_call ~always_retry fully_qualified_route input


let app_remove_categories ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "removeCategories"]
    | None -> [app_name_or_id; "removeCategories"]
  DX.api_call ~always_retry fully_qualified_route input


let app_remove_developers ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "removeDevelopers"]
    | None -> [app_name_or_id; "removeDevelopers"]
  DX.api_call ~always_retry fully_qualified_route input


let app_remove_tags ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "removeTags"]
    | None -> [app_name_or_id; "removeTags"]
  DX.api_call ~always_retry fully_qualified_route input


let app_run ?(always_retry=false) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "run"]
    | None -> [app_name_or_id; "run"]
  DX.api_call ~always_retry fully_qualified_route input


let app_uninstall ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "uninstall"]
    | None -> [app_name_or_id; "uninstall"]
  DX.api_call ~always_retry fully_qualified_route input


let app_update ?(always_retry=true) ?alias app_name_or_id input =
  let fully_qualified_route = match alias with
    | Some x -> [app_name_or_id; x; "update"]
    | None -> [app_name_or_id; "update"]
  DX.api_call ~always_retry fully_qualified_route input


let app_new ?(always_retry=false) input = DX.api_call ~always_retry ["app"; "new"] input


let applet_add_tags ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "addTags"] input


let applet_add_types ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "addTypes"] input


let applet_close ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "close"] input


let applet_describe ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "describe"] input


let applet_get ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "get"] input


let applet_get_details ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "getDetails"] input


let applet_list_projects ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "listProjects"] input


let applet_remove_tags ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeTags"] input


let applet_remove_types ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeTypes"] input


let applet_rename ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "rename"] input


let applet_run ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "run"] input


let applet_set_details ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setDetails"] input


let applet_set_properties ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setProperties"] input


let applet_set_visibility ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setVisibility"] input


let applet_new ?(always_retry=false) input = DX.api_call ~always_retry ["applet"; "new"] input


let container_clone ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "clone"] input


let container_describe ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "describe"] input


let container_destroy ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "destroy"] input


let container_list_folder ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "listFolder"] input


let container_move ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "move"] input


let container_new_folder ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "newFolder"] input


let container_remove_folder ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeFolder"] input


let container_remove_objects ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeObjects"] input


let container_rename_folder ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "renameFolder"] input


let file_add_tags ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "addTags"] input


let file_add_types ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "addTypes"] input


let file_close ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "close"] input


let file_describe ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "describe"] input


let file_download ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "download"] input


let file_get_details ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "getDetails"] input


let file_list_projects ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "listProjects"] input


let file_remove_tags ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeTags"] input


let file_remove_types ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeTypes"] input


let file_rename ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "rename"] input


let file_set_details ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setDetails"] input


let file_set_properties ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setProperties"] input


let file_set_visibility ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setVisibility"] input


let file_upload ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "upload"] input


let file_new ?(always_retry=false) input = DX.api_call ~always_retry ["file"; "new"] input


let gtable_add_rows ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "addRows"] input


let gtable_add_tags ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "addTags"] input


let gtable_add_types ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "addTypes"] input


let gtable_close ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "close"] input


let gtable_describe ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "describe"] input


let gtable_get ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "get"] input


let gtable_get_details ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "getDetails"] input


let gtable_list_projects ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "listProjects"] input


let gtable_next_part ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "nextPart"] input


let gtable_remove_tags ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeTags"] input


let gtable_remove_types ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeTypes"] input


let gtable_rename ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "rename"] input


let gtable_set_details ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setDetails"] input


let gtable_set_properties ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setProperties"] input


let gtable_set_visibility ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setVisibility"] input


let gtable_new ?(always_retry=false) input = DX.api_call ~always_retry ["gtable"; "new"] input


let job_describe ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "describe"] input


let job_stream_log ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "streamLog"] input


let job_terminate ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "terminate"] input


let job_new ?(always_retry=false) input = DX.api_call ~always_retry ["job"; "new"] input


let notifications_get ?(always_retry=true) input = DX.api_call ~always_retry ["notifications"; "get"] input


let notifications_mark_read ?(always_retry=true) input = DX.api_call ~always_retry ["notifications"; "markRead"] input


let project_add_tags ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "addTags"] input


let project_clone ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "clone"] input


let project_decrease_permissions ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "decreasePermissions"] input


let project_describe ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "describe"] input


let project_destroy ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "destroy"] input


let project_invite ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "invite"] input


let project_leave ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "leave"] input


let project_list_folder ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "listFolder"] input


let project_move ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "move"] input


let project_new_folder ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "newFolder"] input


let project_remove_folder ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeFolder"] input


let project_remove_objects ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeObjects"] input


let project_remove_tags ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeTags"] input


let project_rename_folder ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "renameFolder"] input


let project_set_properties ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setProperties"] input


let project_subscribe ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "subscribe"] input


let project_unsubscribe ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "unsubscribe"] input


let project_update ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "update"] input


let project_new ?(always_retry=false) input = DX.api_call ~always_retry ["project"; "new"] input


let record_add_tags ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "addTags"] input


let record_add_types ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "addTypes"] input


let record_close ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "close"] input


let record_describe ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "describe"] input


let record_get_details ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "getDetails"] input


let record_list_projects ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "listProjects"] input


let record_remove_tags ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeTags"] input


let record_remove_types ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "removeTypes"] input


let record_rename ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "rename"] input


let record_set_details ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setDetails"] input


let record_set_properties ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setProperties"] input


let record_set_visibility ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "setVisibility"] input


let record_new ?(always_retry=false) input = DX.api_call ~always_retry ["record"; "new"] input


let system_find_affiliates ?(always_retry=true) input = DX.api_call ~always_retry ["system"; "findAffiliates"] input


let system_find_apps ?(always_retry=true) input = DX.api_call ~always_retry ["system"; "findApps"] input


let system_find_data_objects ?(always_retry=true) input = DX.api_call ~always_retry ["system"; "findDataObjects"] input


let system_find_jobs ?(always_retry=true) input = DX.api_call ~always_retry ["system"; "findJobs"] input


let system_find_projects ?(always_retry=true) input = DX.api_call ~always_retry ["system"; "findProjects"] input


let system_find_users ?(always_retry=true) input = DX.api_call ~always_retry ["system"; "findUsers"] input


let system_find_project_members ?(always_retry=true) input = DX.api_call ~always_retry ["system"; "findProjectMembers"] input


let system_shorten_url ?(always_retry=true) input = DX.api_call ~always_retry ["system"; "shortenURL"] input


let user_describe ?(always_retry=true) object_id input = DX.api_call ~always_retry [object_id; "describe"] input


let user_update ?(always_retry=false) object_id input = DX.api_call ~always_retry [object_id; "update"] input

